#Base OS
FROM node:22-alpine AS builder

#Working Directory
WORKDIR /app

#Copy Source Code to Container
COPY package*.json ./

#Run the build commands
RUN npm ci --omit=dev

##### Part of the production play

#Base OS
FROM node:22-alpine AS Production

#Working Directory
WORKDIR /app

#Copy Source Code to Container  for production 
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./
COPY . .

#EXPOSE the ports
EXPOSE 4000
USER node

CMD ["npm", "start"]